### ISSUE TITLE
fn.nth(3, "abc") == nil

### ISSUE THREAD

**Issue by stuta** [rtsisyk/luafun#17]
Hello. Here is simple test case:

print(fn.nth(3, {"a", "b", "c"})) -- prints c
print(fn.nth(2, "abc")) -- prints b
print(fn.nth(3, "abc")) -- prints nil

**Comment by stuta** [comment]
four how to fix:
local nth = function(n, gen_x, param_x, state_x)
    assert(n > 0, "invalid first argument to nth")
    -- An optimization for arrays and strings
    if gen_x == ipairs then
        return param_x[n]
    elseif gen_x == string_gen then
        if n <= #param_x then -- must be <=, not <

**Comment by rtsisyk** [comment]
Thanks for this report. Fixed.
