### ISSUE TITLE
items, keys, values (pairs support)

### ISSUE THREAD

**Issue by Eloff** [rtsisyk/luafun#7]
The problem currently is that pairs doesn't work with fun, because it returns the key and value instead of key(state), key, value.

This means there is no way to iterate over sparse arrays and mixed tables.

I'd propose adding an items(tbl) iterator that works with a modified pairs to return all key, value pairs in the table. Likewise values() which can easily be defined as iter(pairs(tbl)). keys is maybe not needed because you can just ignore the value from items().

In moonscript:

    items = (tbl) ->
        gen = (param, state) ->
              k, v = next param, state
              return k, k, v

        return iter gen, tbl, nil

    values = (tbl) -> iter pairs(tbl)

What do you guys think?

**Comment by rtsisyk** [comment]
Fixed long time ago.
